version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5050:5050"
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - DB_NAME=cdc_app
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - CLOUDINARY_URL=${CLOUDINARY_URL:-}
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
